(in-package #:eloquent.mvc.request)

(defclass <request> (<http-request>)
  ((extras :documentation "The keys and values set by middlewares"
           :initarg :extras
           :initform (make-hash-table :test 'eql)
           :reader request-extras
           :type hash-table))
  (:documentation "Request includes the HTTP request and extra information generated by middlewares"))
