(in-package #:eloquent.mvc.request)

(defclass <request> (<http-request>)
  ((extras :documentation "The keys and values set by middlewares"
           :initarg :extras
           :initform (make-hash-table :test 'eql)
           :reader request-extras
           :type hash-table))
  (:documentation "Request includes the HTTP request and extra information generated by middlewares"))

(defun getextra (key req)
  (declare (type <request> req))
  (with-slots (extras) req
    (gethash key extras)))

(defun (setf getextra) (value key req)
  (declare (type <request> req))
  (with-slots (extras) req
    (setf (gethash key extras) value)))
